### ISSUE TITLE
Add version check and improve doc

### ISSUE THREAD

**Issue by nandusri** [SriNandan33/githunt#2]
I installed this library with python 3.6.9 but it is not compatible with 3.6. I had to check setup.py to know the version it is compatible with. So it is good to have a check on the version, show a message if the version is below 3.7. and include required python version in README

**Comment by SriNandan33** [comment]
Thanks @nandusri  for pointing this out. I shall fix it in couple of days and update you.

**Comment by SriNandan33** [comment]
Thanks @kc8 for contributing to this issue (merged #3 ). Closing it.
